version: '3'
services:
  redis1:
    container_name: redis-db-1
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/dummy.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis2:
    container_name: redis-db-2
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/dummy.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  redis3:
    container_name: redis-db-3
    image: redis:latest
    ports:
      - "6381:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/dummy.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
